# Generated by Django 5.0.1 on 2024-01-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vulgar_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Beeyard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apiculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beeyards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('queen_age', models.DateField()),
                ('bee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='apiculture_app.beetype')),
                ('bee_yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='apiculture_app.beeyard')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.FloatField()),
                ('beehyve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatherings', to='apiculture_app.hive')),
            ],
        ),
        migrations.CreateModel(
            name='Contamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AAM', 'acarapisose des abeilles mellifères'), ('LAAM', 'loque américaine des abeilles mellifères'), ('LEAM', 'loque européenne des abeilles mellifères'), ('ICR', 'infestation par le petit coléoptère des ruches (Aethina tumida)'), ('IAT', "infestation des abeilles mellifères par l'acarien Tropilaelaps"), ('VAM', 'varroose des abeilles mellifères.')], max_length=4)),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField(blank=True)),
                ('beehyve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contaminations', to='apiculture_app.hive')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intervention_type', models.CharField(choices=[('RCS', 'Royal Cell Supress'), ('HC', 'Health Check'), ('SD', 'Sirop Distribution'), ('PH', 'Pose de hausses'), ('D', 'Desctruction'), ('MAE', "Multiplication artificielle de l'essaim")], max_length=3)),
                ('traitement', models.CharField(blank=True, choices=[('AP', 'apivar'), ('AO', 'acide oxalique'), ('AF', 'antifongique')], max_length=2)),
                ('beehyve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='apiculture_app.hive')),
            ],
        ),
    ]
