# Generated by Django 5.0.1 on 2024-01-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiculture_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contamination',
            old_name='beehyve',
            new_name='beehive',
        ),
        migrations.RenameField(
            model_name='gathering',
            old_name='beehyve',
            new_name='beehive',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='beehyve',
            new_name='beehive',
        ),
    ]
