# Generated by Django 5.0.1 on 2024-01-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiculture_app', '0002_rename_beehyve_contamination_beehive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gathering',
            name='beehive',
        ),
        migrations.AddField(
            model_name='gathering',
            name='intervention',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gathering', to='apiculture_app.intervention'),
        ),
    ]
