# Generated by Django 5.0.1 on 2024-01-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiculture_app', '0004_alter_intervention_intervention_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('EA', 'en attente'), ('D', 'détruite')], default='A', max_length=4),
        ),
    ]
