# Generated by Django 5.0.1 on 2024-01-13 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiculture_app', '0005_hive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='intervention',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatherings', to='apiculture_app.intervention'),
        ),
    ]
